export function AboutPage() {
  return (
    <div className="about md">
      <h1>About arewehuman</h1>
      <p>
        Readers increasingly cannot tell whether a text was written by a person or generated by a language model, and a statement such as
        "written without AI" is easy to make and impossible to check. arewehuman is a Markdown editor that records how a document was written,
        so that the finished text can be shared together with its history.
      </p>
      <h2>What is recorded</h2>
      <p>
        Every character in the document gets an identifier, the time it was inserted (to the millisecond), and its source: <em>typed</em>,{" "}
        <em>pasted</em> from outside the document, <em>copied</em> from elsewhere in the same document, <em>imported</em> from an existing file,
        or <em>other</em> (for example dictation or autocorrect, which arrive without a keystroke). Deletions, undo, and moves are recorded with
        their times and positions.
      </p>
      <p>
        The values of deleted characters are never recorded. If you write a sentence and then erase it, the history shows that a passage of
        that length existed at that place and time, but not what it said. Text that survives to the final version is known, because it is in
        the final version. The same rule applies to browser storage: only the current text and the event log are saved.
      </p>
      <h2>Files</h2>
      <p>
        Exporting gives two files: <code>name.md</code>, the document itself, and <code>name.prov.json</code>, which contains the same text
        plus the full event log. The provenance file alone is enough to verify and replay the document. The <a href="#/view">Replay</a> page
        replays the log, checks that it reproduces the text exactly, checks the hash chain, and plays back the writing of the document at a
        choice of speeds.
      </p>
      <h2>What this does and does not show</h2>
      <p>
        A consistent history with human keystroke timing is reasonable evidence that the text was typed by a person. It is not a proof.
        Everything runs in your browser, so a determined person could write a program that produces a plausible history, or type out
        AI-generated text by hand. The hash chain detects later edits to a file but not a history that was fabricated from the start. We intend
        to add server-signed timestamps, which would show that a history grew in real time, but even that cannot distinguish a person typing
        their own words from a person transcribing someone else's.
      </p>
      <p>
        Note also that keystroke timing is somewhat identifying: the rhythm of a person's typing can be used to recognize them. Share
        provenance files with that in mind.
      </p>
      <p>
        Inspired by Dan Romik's <a href="https://blog.danromik.com/on-provably-writing-without-ai">ReelDocs</a>. Unlike ReelDocs, arewehuman
        does not keep deleted text and needs no server. Source code and file format:{" "}
        <a href="https://github.com/magland/arewehuman">github.com/magland/arewehuman</a>.
      </p>
    </div>
  );
}
